services:
  - type: web
    name: sperekyp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: JWT_SECRET_KEY
        generateValue: true
